sudo: false
cache:
- pip
language: python
python:
  - '3.5'

env:
- SANIC=0.1.9

install:
  - pip install -U setuptools pep8 coverage docutils pygments sanic==$SANIC multidict aiohttp

script:
  - coverage erase
  - nosetests --with-coverage --cover-package=sanic_cors
  - python setup.py clean build install

after_success:
  - pep8 sanic_cors.py

#deploy:
#  provider: pypi
#  user: ashleysommer
#  password: password
#  distributions: "sdist bdist_wheel"
#  on:
#    tags: true
#    repo: ashleysommer/sanic-cors
#    condition: $TRAVIS_PYTHON_VERSION != *3.5* # Ensures we release a 3.5 wheel
